events {}

http {
  server_tokens off;
  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  upstream mediamtx_hls {
    server mediamtx:8888;
  }

  upstream mediamtx_webrtc {
    server mediamtx:8889;
  }

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;
  ssl_certificate /etc/nginx/certs/server.crt;
  ssl_certificate_key /etc/nginx/certs/server.key;

  server {
    listen 8888 ssl;
    server_name _;

    location = /healthz {
      add_header Content-Type text/plain;
      return 200 'ok\n';
    }

    location / {
      proxy_pass http://mediamtx_hls;
    }
  }

  server {
    listen 8889 ssl;
    server_name _;

    location = /healthz {
      add_header Content-Type text/plain;
      return 200 'ok\n';
    }

    location / {
      proxy_pass http://mediamtx_webrtc;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
  }
}